<?php
$header = get_sub_field('header_text');
$post_list_type = get_sub_field('post_list_type');
$category_ids = get_sub_field('category_id');
$individual_posts = get_sub_field('individual_post');
$custom_post_type = get_sub_field('custom_post_type');
$count = get_sub_field('number_of_posts');
$show_date = get_sub_field('show_date');
$show_date = get_sub_field('show_date');
$show_excerpt = get_sub_field('show_excerpt');
$show_image = get_sub_field('show_image');

// checks if user has selected specific
// taxonomy terms and set the query accordingly
if ( $post_list_type == "Posts by Categories" ){
	$args = array(
        'category__in' => $category_ids,
    	'posts_per_page' => $count,
    	'post_type' => 'post',
    	'orderby' => 'date',
        'order' => 'DESC'
    );
} elseif ( $post_list_type == "Select Individual Posts" ){
    // redefine $list_posts - individual posts are already selected
    $list_posts = $individual_posts;
} elseif ( $post_list_type == "Custom Post Types" ) {
	$args = array(
			'post_type' => $custom_post_type,
			'posts_per_page' => $count,
			'orderby' => 'title',
			'order' => 'ASC'
		);
} else {
    // default args
    $args = array(
    	'posts_per_page' => $count,
    	'post_type' => 'post',
    	'orderby'=> 'date',
    	'order' => 'DESC'
    );
}

if (!empty($header)) {
    echo '<h2 class="uw-mini-bar uw-content-box-header">' . $header . '</h2>';
}
if ( $post_list_type !== "Select Individual Posts") {
    // get array of posts matching defined $args
    $list_posts = get_posts($args);
}
// Checking for array of posts and has posts
if ( is_array($list_posts) && !empty($list_posts) ) {
    echo '<ul class="uw-posts-listing">';
    global $post;
    // for each item of array, put it in $post
    foreach( $list_posts as $post ) {
        setup_postdata( $post );
        echo '<li class="uw-post align-middle">';
        	// check post for featured image
        	if( $show_image  && has_post_thumbnail() ) {
                echo '<div class="uw-post-img align-self-top">';
            	echo wp_get_attachment_image(get_post_thumbnail_id($post->ID));
                echo '</div>';
            }
            echo '<div class="uw-post-text">';
                echo '<h3><a href="' . get_permalink($post->ID) . '">' . get_the_title() . '</a></h3>';

                if ($show_excerpt) {
                  echo '<p class="uw-post-excerpt">' . get_the_excerpt($post->ID) . '</p>';
                }
                if ( $show_date ) {
                  echo '<span class="uw-post-date">' . get_the_date() . '</span>';
                }
            echo '</div>';
        echo '</li>';
    }

    /* Show a "more" link that changes based on the kind of post list.
     * Currently only shows a link if the user selects All Posts or a Custom Post Type.
    */

    if ( $post_list_type == "All Posts" || $post_list_type == "" ) {
        // Check if there is a static home page set
        if ( get_option( 'show_on_front' ) == 'page' ) {
            // Check if there is a page set to display posts. Goes to a
            // generic posts query if no blog page is selected.
            if ( get_option( 'page_for_posts' ) ) {
                $blog_link_url = get_permalink(get_option('page_for_posts'));
            } else {
                $blog_link_url = home_url('/?post_type=post');
            }
        // Link goes to the home page if that is the blog page
        } else {
            $blog_link_url = home_url( '/' );
        }

        echo '<li><a class="uw-more-link" href="' . esc_url($blog_link_url) . '">'
        . 'More News ' . get_svg('uw-symbol-more', array("aria-hidden" => "true")) . '</a></li>';

    }

    if ( $post_list_type == "Custom Post Types" ) {
        $custom_post_title = get_post_type_object( $custom_post_type );
        echo '<li><a class="uw-more-link" href="' . get_post_type_archive_link( $custom_post_type )
        . '">' . $custom_post_title->labels->name . ' '
        . get_svg('uw-symbol-more', array("aria-hidden" => "true")) . '</a></li>';
    }

    if ( $post_list_type == "Posts by Categories" && !empty( $category_ids ) ) {
        $categories = get_categories( array('include' => $category_ids) );
        $links_out = "";
        foreach ($categories as $category) {
            $links_out .= '<li><a class="uw-more-link" href="' . get_category_link( $category->cat_ID )
        . '">More <i>' . $category->name . '</i> posts '
        . get_svg('uw-symbol-more', array("aria-hidden" => "true")) . '</a></li>';
        }

        /**
         * Filter the category more links output
         * If you don't want any links, add a 'latest_posts_category_more_links' filter function
         * in your child theme that returns false
         *
         * @param string $output Markup generated by default
         * @param Array $category_ids The chosen categories
         */
        $links_out = apply_filters( 'latest_posts_category_more_links', $links_out, $category_ids );

        echo $links_out;
    }

    echo '</ul>';
} else {
  echo '<p>No posts currently available to show</p>';
}
wp_reset_postdata();
?>
